### ISSUE TITLE
Inefficient fromCode lookup

### ISSUE THREAD

**Issue by maxgurewitz** [ohanhi/keyboard-extra#1]
It looks like you're doing a linear search for your `Key` on every key press

```
fromCode : KeyCode -> Key
fromCode code =
    codeBook
        |> List.filter (((==) code) << fst)
        |> List.map snd
        |> List.head
        |> Maybe.withDefault Other
```

This code would be more efficient if codebook were a dict e.g.

```
codeDict = Dict.fromList codeBook

fromCode : KeyCode -> Key
fromCode code =
    codeDict
        |> Dict.get code
        |> Maybe.withDefault Other
```

This also has the benefit of making terser code!

**Comment by ohanhi** [comment]
Yes. I will do this. :)

Would be interesting to see some benchmarks about the change though, do you have any idea how that could be done?

**Comment by maxgurewitz** [comment]
@ohanhi not an expert in benchmarking by any means, but I'd write a small script for triggering key events and then follow the guidelines in

https://developer.chrome.com/devtools/docs/heap-profiling
https://developer.chrome.com/devtools/docs/cpu-profiling
