### ISSUE TITLE
no way to tell what key is being pressed/released

### ISSUE THREAD

**Issue by mordrax** [ohanhi/keyboard-extra#14]
My use case is that i'm trying to see when the user has pressed one of the directions on the numpad + the shift key. So let's say they pressed shift, then they pressed 9 (PgUp) which represents NE.

To do this, ideally, I'd match on the keycode for Numpad 9, and do a test for isPressed on shift. 

The problem is matching on keycode for Numpad 9. When a Msg comes in for a keypress, the Msg type is hidden, so I only have the current model and the new model. There is no easy way of finding out what just got pressed or released. I'd have to use `pressedDown: Model -> List Key` on the existing model and then diff that with the new model to work out what key was just pressed or released. Then I'd have to work out whether it was pressed or released.

If the Msg type was exposed, then I could get the KeyCode from the msg and use fromCode to turn that into a Key. That would solve my use case.

**Comment by ohanhi** [comment]
@mordrax I know it's been a while, but I finally could get back to this. What do you think, does my new [`updateWithKeyChange`](https://github.com/ohanhi/keyboard-extra/blob/cd5973c/src/Keyboard/Extra.elm#L103-L139) seem like a nice solution to your problem?

If it does, I will publish it as a part of the next release. It will be 2.0.0, as I removed some unnecessary cruft from the API in general.

**Comment by ohanhi** [comment]
Actually, could you elaborate on whether your case? Would you have been satisfied just by having subscriptions like this:

```elm
downs : (Key -> msg) -> Sub msg
```
```elm
ups : (Key -> msg) -> Sub msg
```

and handling stuff on your own from then on?

Just a reminder, this would result in repeating messages when the user presses and holds a key.

**Comment by mordrax** [comment]
Hey @ohanhi thanks for getting back to me. Yes, I think having a subscription would solve my problem.

So I could then listen for a direction key, and use the `isPressed` to work out if the shift key is being held down. If so, I would run in that direction instead of walk.

This makes key combos much easier.

However, re-reading what I wrote, I realised that this is not possible unless you expose Msg:
https://github.com/ohanhi/keyboard-extra/blob/1.2.0/src/Keyboard/Extra.elm#L15

Because otherwise I wouldn't know whether it's Down or Up

**Comment by ohanhi** [comment]
With the subscriptions, you would have your own Msgs for `ups` and `downs`. Just like with the elm-lang/keyboard.

The other option is what I linked to earlier: a special kind of update that figures out the change for you.
```elm
updateWithKeyChange : Msg -> Model -> ( Model, Maybe KeyChange )
```

where  KeyChange is

```elm
type KeyChange
    = KeyDown Key
    | KeyUp Key
```

Which one would you prefer?

**Comment by ohanhi** [comment]
@mordrax I decided to include both options, they are live here: http://package.elm-lang.org/packages/ohanhi/keyboard-extra/2.0.0

I am closing this now, feel free to open another issue if this does not solve your case after all.

**Comment by mordrax** [comment]
I see... `updateWithKeyChange` please :) That gives me both the current state of the keyboard and the last action performed.

EDIT: Ah excellent, I had my github issues tab open from before you closed it, thanks for adding that feature! :)
