### ISSUE TITLE
Update misleading

### ISSUE THREAD

**Issue by amilner42** [ohanhi/keyboard-extra#17]
Why have `update` return a pair with the Cmd if the cmd is always `Cmd.none`.

I get that it fits nicely into the Elm setup, but I find this misleading and think it makes more sense to just return the new model.

**Comment by amilner42** [comment]
https://github.com/ohanhi/keyboard-extra/blob/master/src/Keyboard/Extra.elm#L89
https://github.com/ohanhi/keyboard-extra/blob/master/src/Keyboard/Extra.elm#L96

**Comment by amilner42** [comment]
Along these lines, I'd say `init` is also misleading, I think it makes more sense to just use the model, pairing with `Cmd.none` doesn't make sense to me.

**Comment by ohanhi** [comment]
Yeah, I know. I suppose I was just kind of wary of making choices that might cause breaking changes in the future in case I did need some commands later. And now it's a breaking change if I remove it...

**Comment by amilner42** [comment]
Ya fair enough, still seems confusing to me to have it there in case in the future...with that logic we could have a _lot_ of things in the code that aren't currently needed.

But I get your point. Fair enough.

**Comment by ohanhi** [comment]
Just to keep you informed, I have this change in a branch at the moment, and I do plan to release it once the other outstanding issue seems to be resolved. :)
