### ISSUE TITLE
A way to subscribe without boilerplate

### ISSUE THREAD

**Issue by maartenschumacher** [ohanhi/keyboard-extra#5]
I know it's the recommended way to achieve modularity, but to wire `Keyboard.Extra`'s init, model, update and subscription into my own seems like a lot of wiring code just to get notified when `arrowDirection` changes.

I've tried making a module that exposes `arrowDirection` as a subscription, just like `Keyboard` exposes keypresses as a subscription, but it was very complicated, and there is not much documentation. Have you tried / considered it?

**Comment by ohanhi** [comment]
Unfortunately, this isn't possible really. `elm-lang/keyboard` has an [effect manager](http://guide.elm-lang.org/effect_managers/). There is no documentation on how to create them as of yet, and using them in a package means the Elm team needs to approve (whitelist) the package.
