### ISSUE TITLE
Left shift not detected

### ISSUE THREAD

**Issue by xarvh** [ohanhi/keyboard-extra#8]
Using Chromium 51.0.2704.79, `isPressed Shift model` will detect a right Shift but not a left Shift.
As far as I can tell, there is no way to detect a left Shift.

Using just the `Keyboard` module, both shifts are detected as the same code, 16.

**Comment by ohanhi** [comment]
This is very strange indeed. Does the problem still exist, and if so, which operating system are we talking about?

**Comment by xarvh** [comment]
Seems to work now.

**Comment by xarvh** [comment]
FWIW, I tested it on Chromium 53.0.2785.143, Ubuntu.

**Comment by ohanhi** [comment]
Cool, nice to hear! 👍
