### ISSUE TITLE
fromCode not exposed in current release

### ISSUE THREAD

**Issue by jw3126** [ohanhi/keyboard-extra#9]
It would be cool to have fromCode, toCode exposed. It seems that they are implemented in 1.1.0 already, but not exposed?

**Comment by ohanhi** [comment]
This has been implemented in 1.3.0. :tada:

**Comment by joneshf** [comment]
`1.3.0` has not been published yet. The latest on elm-package is `1.1.0`.

**Comment by ohanhi** [comment]
Sorry, I should have been clearer. 1.3.0 will be visible on elm-package when the new version of Elm (0.18) becomes the standard.

**Comment by joneshf** [comment]
Can we get these functions in 0.17?
